import { type NextPage } from "next";
import { useSession } from "next-auth/react";
import Head from "next/head";

const Home: NextPage = () => {
  const { data: sessionData } = useSession();

  return (
    <>
      <Head>
        <title>Start - StudySprint</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="flex flex-col">
        <div>
          {sessionData && sessionData.user && (
            <h1 className="text-2xl">Hey, {sessionData.user.name} 👋</h1>
          )}
        </div>

        <section className="mt-8 flex flex-col gap-4">
          <h2 className="text-2xl">Dein Tagesplan 📔</h2>
          <div className="h-40 w-full bg-slate-700"></div>
        </section>

        <section className="mt-8 flex flex-col gap-4">
          <h2 className="text-2xl">Goals 🎯</h2>
          <div className="h-40 w-1/2 bg-slate-700"></div>
        </section>

        <section className="mt-8 flex flex-col gap-4">
          <h2 className="text-2xl">
            Hier ist eine Playlist um dich in Stimmung zu bekommen 🎧
          </h2>
          <div className="h-40 w-full bg-slate-700"></div>
        </section>

        <section className="mt-8 flex flex-col gap-4">
          <h2 className="text-2xl">Deine Lernsets</h2>
          <div className="h-40 w-full bg-slate-700"></div>
        </section>
      </div>
    </>
  );
};

export default Home;
